const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/index', (req, res) => res.render('pages/index'))
  .get('/inicio', (req, res) => res.render('pages/inicio'))
  .get('/inscreva-se', (req, res) => res.render('pages/inscreva-se'))
  .get('/criaTarefa', (req, res) => res.render('pages/criaTarefa'))
  .get('/criaEvento', (req, res) => res.render('pages/criaEvento'))
  .get('/criaHorario', (req, res) => res.render('pages/criaHorario'))
  .get('/eventos', (req, res) => res.render('pages/eventos'))
  .get('/perfil', (req, res) => res.render('pages/perfil'))
  .get('/tarefas', (req, res) => res.render('pages/tarefas'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
